apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    env: miztiik-prod
spec:
  containers:
    - name: busybox
      image: busybox
    imagePullPolicy: IfNotPresent
      command: [ "sh", "-c", "sleep 1h" ]