apiVersion: apps/v1
kind: Deployment
metadata:
  name: k-shop-01
  namespace: fargate-ns-01
  labels:
    app: k-shop-01
spec:
  replicas: 3
  selector:
    matchLabels:
      owner: miztiik_automation
      compute_provider: fargate
  template:
    metadata:
      labels:
        owner: miztiik_automation
        compute_provider: fargate
    spec:
      containers:
        - name: k-shop-nginx
          image: nginx:latest
          ports:
            - name: http
              containerPort: 80