apiVersion: v1
kind: Pod
metadata:
  name: spot-nginx
  labels:
    env: miztiik-prod
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  nodeSelector:
    app: miztiik_spot_ng





apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  namespace: <same-namespace-as-your-fargate-profile>
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - name: http
              containerPort: 80